# Generated by Django 5.2.8 on 2025-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=60)),
                ('img_evento', models.ImageField(upload_to='img_eventos/')),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_historia', models.ImageField(upload_to='img_historia/')),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
    ]
