# Generated by Django 5.2.8 on 2026-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0002_eventos_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=100)),
                ('mensagem_contato', models.CharField(max_length=500)),
                ('data_envio_contato', models.DateField(auto_now_add=True)),
                ('horas_envio_contato', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_coordenador', models.CharField(max_length=100)),
                ('bio_coordenador', models.CharField(max_length=200)),
                ('icone_coordenador', models.ImageField(upload_to='icones_coordenadores/')),
            ],
        ),
        migrations.DeleteModel(
            name='Orientadores',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='descricao',
            new_name='desc_evento',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='nome_evento',
            new_name='titulo_evento',
        ),
        migrations.RenameField(
            model_name='historia',
            old_name='descricao',
            new_name='desc_historia',
        ),
        migrations.AddField(
            model_name='grupos',
            name='icone_bolsista',
            field=models.ImageField(null=True, upload_to='icones_bolsistas/'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='nome_bolsista',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
