# Generated by Django 5.2.8 on 2026-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0003_contato_coordenadores_delete_orientadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='mensagem_contato',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='nome_grupo',
            field=models.CharField(max_length=30),
        ),
    ]
