# Generated by Django 5.2.8 on 2026-02-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0004_alter_contato_mensagem_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='desc_historia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historia',
            name='img_historia',
            field=models.ImageField(blank=True, upload_to='img_historia/'),
        ),
    ]
