# Generated by Django 5.2.8 on 2026-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0005_alter_historia_desc_historia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='desc_grupo',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem_contato',
            field=models.TextField(),
        ),
    ]
