# Generated by Django 5.2.8 on 2026-02-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0006_grupos_desc_grupo_alter_contato_mensagem_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='desc_evento',
            field=models.TextField(),
        ),
    ]
