# Generated by Django 5.2.8 on 2026-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0007_eventos_data_alter_eventos_desc_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='sobre',
            field=models.URLField(null=True),
        ),
    ]
