# Generated by Django 5.2.8 on 2026-10-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuarte', '0008_eventos_sobre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='horas_envio_contato',
            new_name='hora_envio_contato',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='data',
            new_name='data_evento',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='sobre',
            new_name='link_evento',
        ),
    ]
